Compatibility: Gravity Forms + Yoast fix
siteorigin/siteorigin-panels pull request #806
Opened 2020-08-24 14:13 UTC by AlexGStapleton

Resolve https://github.com/siteorigin/siteorigin-panels/issues/321

This PR will run [gform_disable_print_form_scripts](https://docs.gravityforms.com/gform_disable_print_form_scripts/) when the Gravity Forms widget is added to a Page Builder layout.

2020-08-24 18:46 UTC, Misplon commented
Thanks. The issue seems to be persisting for me. Here is what I see:

![Edit_Page_‹_SiteOrigin_—_WordPress](https://user-images.githubusercontent.com/789159/91083576-d09add80-e64a-11ea-8f48-0298e21056c0.jpg)

2020-08-24 21:43 UTC, AlexGStapleton commented
The provided fix won't adjust the setting as that's overly complicated and potentially confusing ("why does this setting keep getting re-enabled?"). Instead, it overrides the setting on the fly using a filter.

Can you please [send me a copy of the form](https://docs.gravityforms.com/exporting-a-form-from-gravity-forms/) you're testing? To be clear, this issue is only visible when using the form, and not while editing it.

2020-08-25 08:42 UTC, Misplon commented
> The provided fix won't adjust the setting as that's overly complicated and potentially confusing ("why does this setting keep getting re-enabled?"). Instead, it overrides the setting on the fly using a filter.

Thanks, I'm not expecting this PR to adjust the setting, my screenshot is just showing everything I see.

> To be clear, this issue is only visible when using the form, and not while editing it.

Using the form I'm testing with, there isn't an error on the site front-end using the develop branch. Does the form need conditional fields?

When enabling the Disable script output setting, the JS error does resolve in the admin. Should we not also use the filter in the admin to prevent the error?

2020-08-25 08:47 UTC, Misplon commented
Test form: 
[gravityforms-export-2020-08-25.json.zip](https://github.com/siteorigin/siteorigin-panels/files/5122474/gravityforms-export-2020-08-25.json.zip)

2020-08-26 11:31 UTC, AlexGStapleton commented
I'm not getting the error message you're getting when editing the widget. I'm also having trouble replicating this error again. 

> Does the form need conditional fields?

Yes. [Here's the form](https://drive.google.com/uc?id=1f48BtNFq6KRvvSM7DClvcmIh8TQKS3TH) I was using when I initially created this PR. Mind you, I'm having trouble replicating it now. :/
I hate to say it, but it might be worth closing this and suggesting disabling "disable script output" if it happens. It feels safer.

2020-08-26 15:55 UTC, Misplon commented
Thanks, I've tried your form and I've tried adding a conditional field to my first test form, I'm now not able to recreate a console error in the admin or front-end.

2021-05-17 09:21 UTC, Misplon commented on compat/gravity-forms.php
> + * Disable Gravity Disable Print Form Scirpts.
Gravity Forms Disable Print Scripts?

2021-05-17 09:31 UTC, Misplon requested changes
Description update/typo correction required, otherwise all good.

2021-05-17 17:49 UTC, Misplon approved these changes

2021-05-20 17:01 UTC, Misplon commented
@AlexGStapleton Can you take a look at the above conflict? Thanks, mate.

2021-05-20 17:08 UTC, AlexGStapleton commented
Done.

2021-05-20 17:10 UTC, merged